### ISSUE TITLE
cat-select doesn't work with dynamic multiple and readonly parameters

### ISSUE THREAD

**Issue by szabyg** [Catalysts/cat-angular#10]
The parameters `multiple` and `readonly` only work in a hard-coded manner. multiple="false" or readonly="false" still makes the component multi-selactable and readonly. The reason is in the wrapped select2 component.

**Comment by tscheinecker** [comment]
any suggestions on how this could be fixed in a clean way?

**Comment by tscheinecker** [comment]
just noticed (i don't know why i missed this)

multiple and readonly are boolean attributes, meaning that the value is ignored
as soon as the attribute is present it is applied

this has nothing to do with any wrapper, it is just how html works

dynamically changing readonly and disabled works fine with the appropriate directive wrappers (ng-disabled and ng-readonly)

afaik no such thing exists for the multiple attribute as usually you don't want to switch this attribute dynamically

**Comment by szabyg** [comment]
> afaik no such thing exists for the multiple attribute as usually you don't want to switch this attribute dynamically

Well, we do :-)

**Comment by szabyg** [comment]
> dynamically changing readonly and disabled works fine with the appropriate directive wrappers (ng-disabled and ng-readonly)

I think I tried that and it didn't work... I'll try again.

**Comment by szabyg** [comment]
ng-disabled and ng-readonly both work and do the same, thanks!
As explained on https://docs.angularjs.org/error/$compile/selmulti, multiple shouldn't have binding because it breaks the ng-model semantics. We can live with the workaround suggested also on the mentioned page.
