### ISSUE TITLE
cat-sortable default sorting definition

### ISSUE THREAD

**Issue by szabyg** [Catalysts/cat-angular#50]
We would need a default sorting parameter for cat-paginated with cat-sortable.
[It seems](https://github.com/Catalysts/cat-angular/blob/b000aa53bb58b25a76b2e037d14852669c54e915/src/main/javascript/directives/cat-sortable.js#L21) that there's a plan to add directive configuration for default sorting.

**Comment by tscheinecker** [comment]
please provide more details about what exactly you need.

ideally provide me with some markup / code snippet of what you would like to do / how you would like to do it and an explanation about what the expected outcome should be

**Comment by szabyg** [comment]
We resolved this issue in the meantime reusing a wrapper directive.
