### ISSUE TITLE
Make cat-angular to an npm module

### ISSUE THREAD

**Issue by szabyg** [Catalysts/cat-angular#56]
NPM provides frontend dependency management features. Some libraries don't support bower (e.g. angular2). Having two frontend package management mechanisms would be an overkill for us, therefore we decided to go with npm only.
In order to be able to use cat-angular with npm, we need the dist folder to be part of the npm package.

**Comment by szabyg** [comment]
Ping. Plan, opinion?

**Comment by tscheinecker** [comment]
https://www.npmjs.com/package/cat-angular
