### ISSUE TITLE
Search param serialisation broke

### ISSUE THREAD

**Issue by szabyg** [Catalysts/cat-angular#9]
Commit [8b6d8b52a](https://github.com/Catalysts/cat-angular/commit/8b6d8b52aa7841baa1ea73b2048ac1865b5a258d) broke the search filtering in our project. Why was this change necessary? Before you could pass an array or an object into the search and it rendered it into the url like param[]=12&param[]=34 for arrays and as param[asdf]=123 for objects. Now it serializes param=12&param=34 for arrays and param=[oject object] for objects.

**Comment by tscheinecker** [comment]
this actually was requested by another project, as the spring backend didn't correctly handle the list params

**Comment by tscheinecker** [comment]
i reverted back to the previous param encoding in v0.0.26, and also encapsulated the logic into angular service so that custom behaviour can now be achieved via simple decorators
